version: '3'
services:

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dockerPostgresVolume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on:
      - postgres
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    volumes:
      - dockerPGAdminVolume:/var/lib/pgadmin

networks:
  internal_net:
    external: false

volumes:
  dockerPostgresVolume:
    external: true
  dockerPGAdminVolume:
    external: true